name: "Run Tests"
on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash

env:
  # https://docs.astral.sh/uv/guides/integration/github/#using-uv-pip
  UV_SYSTEM_PYTHON: 1

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: "3.7"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.12"
          # - os: ubuntu-latest
          #   python-version: "3.13"
          # python3.13: disabled until tensorflow supports

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Configure environments
        run: |
          python --version

      - name: Install dependencies
        run: |
          uv pip install -e ".[test]"
          python -m imgcat --version

      - name: Run tests
        run: |
          pytest --color=yes -v -s
        env:
          PYTHONIOENCODING: UTF-8
